### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by calum-chamberlain** [dttrugman/GrowClust3D.jl#1]
Mostly because of the example data, this repository is really large (950MiB) and slow to clone (9m 14s on my home network). This makes it difficult to install in docker images , and I haven't actually been able to install it in any docker images yet. 

@dttrugman - what do you think about moving the non-code elements out of this repo to make it lighter? This would most likely mean moving the `examples/data` folder somewhere else. You could set up another github repo for those example data. You might also want to use git [large file storage](https://git-lfs.github.com/) for those files (if you are not already). `examples/data` is 364M on my system, and the `.git` folder is 951M.

To do that and effectively shrink we would need to rewrite the commit history, which is potentially dangerous, but at the moment the repo is unusable in some use cases, and slow to install. I think now would be the best time to do this before this repo gets picked up by more people because anyone who has a version of the repo prior to cleaning will need to re-clone the repo to get the cleaned history. I'm struggling to clean the repo fully - I still end up with large objects in the `.git/pack` directory. 

I will look into this more and try and work out how to fully clean those files from the repo. There are also some large grid files in the test directory that might be better elsewhere.

**Comment by dttrugman** [comment]
Great point @calum-chamberlain, thanks for bringing this up. I will definitely look into this. 

The actual "data" needed in the data directory should not be very large. Likely the issue is the example 3D grids. 

There are a couple of obvious fixes (which are not necessarily exclusive). One would be to move the grid files somewhere else and provide a separate way to download. Another way would be to provide a Julia driver script to generate the travel time tables locally. This would require NonLinLoc to be installed, but I imagine this would be the case for most users who actually want to use that feature.

I think the bigger issues as you say is to figure out how to clean things out properly. Now is the right time to do it though. Any guidance you have on this would be most welcome.

**Comment by calum-chamberlain** [comment]
Thanks Daniel - yes, the 3D grid files are the "issue" (quotes because this really shouldn't be much of an issue, sorry for being picky about repo size!). Each file isn't that large, but git is keeping track of them in each commit which ends up being more of a problem.

Good point on a Julia driver script, that could be handy to help show users how they could make the grid files and shouldn't be too hard to make, and I agree that users wanting to use that feature could be expected to have NonLinLoc installed.

I'm testing a few different cleaning methods now and I will report back here.

**Comment by dttrugman** [comment]
Great, thanks! I'll work on making a driver script and likely also will make a separate repo to download big files as needed.

I took a look again, the current test/ directory is actually quite small; but older versions had big files in them (which again would be tracked).

For all its upsides, this is the downside of version control... ;-)

**Comment by calum-chamberlain** [comment]
I think I might be running into the large old test files as well - I will try and "fix" that history. 

I had all sorts of fun re-writing EQcorrscan history at the start when I accidentally included lots of waveform files... all fun-and-games with git eh?

**Comment by dttrugman** [comment]
It is reassuring at least to know I am not the first person to make that mistake.

**Comment by calum-chamberlain** [comment]
Definitely not the first person, and I'm sure I will screw up and commit some large files somewhere again! 

It looks like now [filter-repo](https://github.com/newren/git-filter-repo) is the recommended way to do this. This seems much faster than older alternatives, and you can give it specific paths to remove, which is what we want. I installed filter-repo through my system package manager which was nice and simple.

What I think you should do is:

```bash
# Back-up your local repo somewhere safe!
mv GrowClust3D.jl GrowClust3D.jl.backup_pre_filter_repo
# Make a fresh clone
git clone https://github.com/dttrugman/GrowClust3D.jl
cd GrowClust3D.jl
# Filter out the examples/data, test/nll-grd, test/data and test/nll-grd3 directories to remove large files
git filter-repo --path examples/data --path test/nll-grd --path test/nll-grd3 --path test/data --invert-paths
```

When I run this filter-repo command the examples/data dir goes, saving space there, and the .git folder shrinks from ~900M to 748K.

You should definitely test the repo before you do anything else. Check that all the files that are needed are there (from my comparisons of commit logs it looks fine to me, only examples/data should be missing from the current tree), and test the examples - you might want to add `examples/data` to `.gitignore` (or just do not add and commit those files) and copy over the `examples/data` folder from your backup to quickly test that the examples still work as expected.

Once you are happy that the repo works and is clean then you will need to force push up to github (`git push --force`). Anyone who has a clone of the repo will then need to re-clone the cleaned repo to get a nice small repo. If they do not and they push to origin then they will run into issues.

Later you can figure out the best way to store those data. If you do use git for tracking the `examples/data` directory elsewhere then it would probably be a good idea to use [git lfs](https://git-lfs.github.com/) to track those files.

This is something that is worth taking your time over - re-writing the commit history can be painful, but I don't think it will be too bad here because there are only 57 commits, you are the only committer and we are just trying to get rid of some large files. Let me know if that doesn't make sense or sounds like a terrible idea!

**Comment by dttrugman** [comment]
This is great, thanks! I'll give it a go and let you know if I run into any issues. It is definitely worth spending time getting this right.

**Comment by dttrugman** [comment]
Ok, I believe I was able to clean things up, and everything has test out nicely. I kept most of the example data on hand with the exception of the 3D travel time grids. There is now a julia script provided that can be used to regenerate them.

**Comment by calum-chamberlain** [comment]
Awesome, thanks so much for that Daniel - cloning the trimmed repo is much faster now. Great!

**Comment by dttrugman** [comment]
Great, thanks for the suggestion!
