### ISSUE TITLE
NLL velocity grid origin not aligned with seismicity

### ISSUE THREAD

**Issue by oliviamark** [dttrugman/GrowClust3D.jl#2]
Hi there,

I'm trying to use GrowClust3D on some earthquakes in the central North Island of New Zealand. We're using 3D velocity grids generated from the nationwide velocity model: https://zenodo.org/record/3779523#.YyKjJuxBy3I

We're getting the following error:
`PROJECTION ORIGIN NOT ALIGNED WITH SEISMICITY`

The origin for the projection is `-41.7638 172.9037 140.0` this lies outside our region of earthquakes which have the following distribution:

`Median event location: 175.79825 -38.3992`
`Longitude Percentiles (1%, 99%): 174.938195 176.44939`
`Latitude Percentiles (1%, 99%): -39.010295 -37.952020000000005`

We're using the following `projection` in the GrowClust parameter file:
`tmerc GRS80 -41.7638 172.9037 140.0`

Is this location check necessary? How would you recommend proceeding?

Cheers

**Comment by dttrugman** [comment]
Good question, thanks! This check was put in more to prevent users from accidentally placing their projection region well away from the seismicity. In your case, I think you should be ok.

I have updated the codes on GitHub (replacing "ERROR" with "Caution"; you can grab the latest or just comment out the "exit()" commands  near those warning lines.
