### ISSUE TITLE
find_moho fails for fine-grained velocity models

### ISSUE THREAD

**Issue by yetinam** [dttrugman/GrowClust3D.jl#5]
Hi @dttrugman ,
I've run into an issue with the `find_moho` function defined here:
https://github.com/dttrugman/GrowClust3D.jl/blob/47743b8a4f1cbb7d792e039eb36350dd583b2711/src/seismotrace.jl#L62-L79
The problem occurs when inputting a fine-grained velocity model that does not have any jumps larger than `dalphaM`. In this case the function calling `find_moho` in [traveltime.jl](https://github.com/dttrugman/GrowClust3D.jl/blob/47743b8a4f1cbb7d792e039eb36350dd583b2711/src/traveltime.jl#L32) will crash. As the parameter `dalphaM` is not accessible here, this crash can not be avoided with configuration parameters. 

Potential solutions that come to my mind are:
- Instead of checking for the size of the jump, detect the moho at the point were a certain velocity gradient is exceeded. Alternatively, one could also combine a gradient condition with an absolute jump condition to be robust to both coarse and fine-grained velocity models.
- Iteratively decrease `dalphaM` until a moho is found.
- Catch the cases were no moho is detected. From what I can tell, it's only used for an optional filtering of refracted phases that could be skipped.
- Make `dalphaM` configurable when calling `make_trace1D_tables` so that users can manually overwrite it if necessary.

**Comment by dttrugman** [comment]
Thanks for pointing this out. Should be fixed now, using a combination of bullet points (1) and (3) above.

Daniel

**Comment by yetinam** [comment]
Thanks for the quick fix!
